spring:
  profiles:
    active: local  #어떤 프로파일을 활성화 할 것인지?
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false #타임리프로 개발된 화면을 수정했을 때 매번 프로젝트를 다시 수행하는걸 방지.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: choi
    password: choi
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #MySQL에서는 Auto_Increment를 어떤식으로 사용하는지 방식, JPA가 사용하는 기본 넘버링을 사용하지 않는다.
    #show-sql: true
    generate-ddl: true

server:
  port: 8010
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

